# Local dev environment with postgresql
services:
  postgres:
    image: postgres:17
    container_name: todo-postgres
    environment:
      POSTGRES_DB: devdb
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpassword
    ports:
      - "5433:5432" # Expose the Postgres database on port 5433 for local development
    volumes:
      - postgres_data:/var/lib/postgresql/data

  fastapi-app:
    build:
      context: .
    container_name: todo-fastapi
    depends_on:
      - postgres
    volumes:
      # Mount the local app directory to the /code/app directory in the container    
      - ./app:/code/app
    ports:
      - "8081:8080"
    env_file:
      - .env

volumes:
  postgres_data:
